### ISSUE TITLE
Various small issues

### ISSUE THREAD

**Issue by robinwhittleton** [fvictorio/p-g-wodehouse_the-white-feather#1]
general:
- semanticate makes a couple of changes
- can you update standardebooks and copy in the latest core.css?

content.opf:
- longdesc: honour -> honor (blurbs are en-US)

preface:
- The Gold Bat is a novel, so remove the quotes and add `<i epub:type="se:name.publication.book">`
- Messrs should be `<abbr epub:type="z3998:name-title">Messrs.</abbr>`

chapter-8:
- remove the class from the `<ol>` as it’s the only one in the book (can style the `ol` directly in the CSS). This means we can drop the se-lint-ignore file too.

chapter-17:
- “Encyclopaedia Britannica” is a book, so can be italicised (and have the quotes removed)

chapter-22:
- particoloured -> parti-coloured as suggested by modernize-spelling

chapter-23:
– Can use a `<q>` element instead of non-semantic `<i>`. You _may_ need to add italics back in the CSS?

colophon:
- Wrap Torsten Gideon Wasastjerna in a `<b epub:type="z3998:personal-name">`

local.css:
- Add the standard dedication CSS: https://standardebooks.org/manual/1.7.4/single-page#7.3.1
- It’d be more normal to use `[epub|type~="z3998:signature"]` instead of `footer p` in SE productions

**Comment by fvictorio** [comment]
Hi @robinwhittleton, thanks a lot for reviewing this. I think I've applied all of your suggestions except these two:

> * can you update standardebooks and copy in the latest core.css?

I did this but there were no changes in the `core.css` file.

> * remove the class from the `<ol>` as it’s the only one in the book (can style the `ol` directly in the CSS). This means we can drop the se-lint-ignore file too.

There is another `<ol>` in the same chapter, and the intention was for them to have different list styles to reproduce what's done in the scans. If I use `ol { ... }` in the CSS, then both will have the same type. Am I missing something here?

I opened a PR for these changes so that they are easier to review: https://github.com/fvictorio/p-g-wodehouse_the-white-feather/pull/2

**Comment by fvictorio** [comment]
With respect to the `<ol>` thing, [here's the relevant page](https://archive.org/details/whitefeather00wodeuoft/page/87/mode/1up).

**Comment by robinwhittleton** [comment]
Sorry, I run the dev version of the tooling and it looks like the changes to core.css were made after the last published version, so don’t worry about that.

On the `ol` I’d somehow missed the second one in the chapter, but that’s OK as we can use `ol:first-of-type`: https://www.w3.org/TR/selectors/#the-first-of-type-pseudo

**Comment by fvictorio** [comment]
> On the `ol` I’d somehow missed the second one in the chapter, but that’s OK as we can use `ol:first-of-type`: https://www.w3.org/TR/selectors/#the-first-of-type-pseudo

Makes sense, done in aefed96d6ac89b5ee53e861271b2bf87d10a39b1

**Comment by robinwhittleton** [comment]
It’s actually just occurred to me that you can also do `<ol type="lower-alpha">`: https://html.spec.whatwg.org/#attr-ol-type. No idea what ereader support is like, so maybe we should stick with what we have.

**Comment by robinwhittleton** [comment]
Either way, this looks ready! Want to merge your feedback branch into main? Then I’ll let Alex know we’re good to go.

**Comment by fvictorio** [comment]
Merged!
